name: Update Deno Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Human: 12am every day

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Update dependencies
        run: deno run -A --import-map=https://deno.land/x/update/deno.json https://deno.land/x/update/mod.ts -b
      - name: Test
        run: deno test -A
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update dependencies
          branch: main
